<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="1" total="6" passed="2">
  <reporter-output>
    <line>
      <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg">Capture screenshot<a/>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg"><img src="/home/kukks/Selenium Learning/Screenshots/error.jpg"height=200 width=200</img><a/>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg">Capture screenshot<a/>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg"><img src="/home/kukks/Selenium Learning/Screenshots/error.jpg"height=200 width=200</img><a/>]]>
    </line>
  </reporter-output>
  <suite name="Learning TestNG" duration-ms="118" started-at="2017-06-21T17:15:07Z" finished-at="2017-06-21T17:15:07Z">
    <groups>
      <group name="high">
        <method signature="TestCase1.doUserReg()[pri:1, instance:testngLearning.TestCase1@42e26948]" name="doUserReg" class="testngLearning.TestCase1"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testngLearning.TestCase3@1e397ed7]" name="doUserReg" class="testngLearning.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testngLearning.TestCase3@1e397ed7]" name="doLogin" class="testngLearning.TestCase3"/>
      </group> <!-- high -->
      <group name="low">
        <method signature="TestCase2.validateTitle()[pri:1, instance:testngLearning.TestCase2@2f686d1f]" name="validateTitle" class="testngLearning.TestCase2"/>
      </group> <!-- low -->
      <group name="medium">
        <method signature="TestCase1.doLogin()[pri:1, instance:testngLearning.TestCase1@42e26948]" name="doLogin" class="testngLearning.TestCase1"/>
      </group> <!-- medium -->
    </groups>
    <test name="Login Test" duration-ms="52" started-at="2017-06-21T17:15:07Z" finished-at="2017-06-21T17:15:07Z">
      <class name="testngLearning.TestCase1">
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:testngLearning.TestCase1@42e26948]" name="LaunchBrowser" is-config="true" duration-ms="1" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:1, instance:testngLearning.TestCase1@42e26948]" name="doLogin" duration-ms="9" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:testngLearning.TestCase1@42e26948]" name="CloseBrowser" is-config="true" duration-ms="1" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:testngLearning.TestCase1@42e26948]" name="LaunchBrowser" is-config="true" duration-ms="3" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testngLearning.TestCase1@42e26948]" name="doUserReg" duration-ms="2" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:testngLearning.TestCase1@42e26948]" name="CloseBrowser" is-config="true" duration-ms="1" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- testngLearning.TestCase1 -->
    </test> <!-- Login Test -->
    <test name="Validate Title Test" duration-ms="8" started-at="2017-06-21T17:15:07Z" finished-at="2017-06-21T17:15:07Z">
      <class name="testngLearning.TestCase2">
        <test-method status="FAIL" signature="validateTitle()[pri:1, instance:testngLearning.TestCase2@2f686d1f]" name="validateTitle" duration-ms="3" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not successful
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at testngLearning.TestCase2.validateTitle(TestCase2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg">Capture screenshot<a/>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg"><img src="/home/kukks/Selenium Learning/Screenshots/error.jpg"height=200 width=200</img><a/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitle -->
      </class> <!-- testngLearning.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test name="Dependency Test" duration-ms="9" started-at="2017-06-21T17:15:07Z" finished-at="2017-06-21T17:15:07Z">
      <class name="testngLearning.TestCase1">
        <test-method status="PASS" signature="CreateDBConn()[pri:0, instance:testngLearning.TestCase1@42e26948]" name="CreateDBConn" is-config="true" duration-ms="14" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateDBConn -->
        <test-method status="PASS" signature="CloseDBConn()[pri:0, instance:testngLearning.TestCase1@42e26948]" name="CloseDBConn" is-config="true" duration-ms="0" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDBConn -->
      </class> <!-- testngLearning.TestCase1 -->
      <class name="testngLearning.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testngLearning.TestCase3@1e397ed7]" name="doUserReg" duration-ms="1" started-at="2017-06-21T22:45:07Z" finished-at="2017-06-21T22:45:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not Reg successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not Reg successfully
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at testngLearning.TestCase3.doUserReg(TestCase3.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg">Capture screenshot<a/>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="/home/kukks/Selenium Learning/Screenshots/error.jpg"><img src="/home/kukks/Selenium Learning/Screenshots/error.jpg"height=200 width=200</img><a/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testngLearning.TestCase3@1e397ed7]" name="doLogin" duration-ms="0" started-at="2017-06-21T22:45:07Z" depends-on-methods="testngLearning.TestCase3.doUserReg" finished-at="2017-06-21T22:45:07Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testngLearning.TestCase3@1e397ed7] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testngLearning.TestCase3@1e397ed7] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
      </class> <!-- testngLearning.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- Learning TestNG -->
</testng-results>
